plugins {
    alias(libs.plugins.android.application)
    id 'com.google.android.libraries.mapsplatform.secrets-gradle-plugin'
}

android {
    namespace 'com.hijiyam_koubou.taplans'
    compileSdk 34

    defaultConfig {
        applicationId "com.hijiyam_koubou.taplans"
        minSdk 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            debuggable true
        }
        debug {
            signingConfig signingConfigs.debug
            debuggable true
            jniDebuggable true
            renderscriptDebuggable true
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildFeatures {
        viewBinding true
    }
    dataBinding {
        enabled true
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout
    implementation libs.lifecycle.livedata.ktx
    implementation libs.lifecycle.viewmodel.ktx
    implementation libs.navigation.fragment
    implementation libs.navigation.ui
    implementation libs.easypermissions.v300

    implementation libs.preference
    implementation libs.support.annotations
    implementation libs.easypermissions

//    implementation libs.play.services.auth
////    implementation libs.play.services.auth.v1600    //    implementation 'com.google.android.gms:play-services-auth:16.0.0'
////    implementation libs.play.services.auth.v1900//    implementation 'com.google.android.gms:play-services-auth:19.0.0'
//    implementation libs.play.services.identity
//    implementation libs.google.api.client
//    implementation libs.google.oauth.client.jetty
//
//    implementation libs.google.api.services.calendar
//    implementation libs.google.http.client.gson     //    implementation 'com.google.http-client:google-http-client-gson:1.26.0'
//    implementation(libs.google.api.client.android) {
//        exclude group: 'org.apache.httpcomponents'
//    }
//    implementation(libs.google.api.services.calendar.vv3rev2141220) {
//        exclude group: 'org.apache.httpcomponents'
//    }
    
    testImplementation libs.junit
    implementation libs.ext.junit
    implementation libs.espresso.core


}
